clear all;
close all;

R1 = 500;
R2 = 2000;
VAL = 5; % +V alimentare
Val = -5; % -V alimentare
A = 1; % Amplitudinea
N = 5; % Nr perioade
F = 500; % Frecventa
semnal = 1;

Fig=figure('Name','Proiect GAC',... % figura interfata
 'Units','normalized',...
 'NumberTitle','off',...
 'Position',[0.35 0.5 0.3 0.3],...
 'Color','#F0F0F0');

uicontrol('Style','pushbutton',... % buton documentatie
 'Units','normalized',...
 'Position',[0.35 0.6 0.3 0.1],...
 'string','DOCUMENTATIE',...
 'Callback','close;start_proiect()');
 %'Callback','open(''document.docx'')'); 

uicontrol('Style','pushbutton',... % buton program
 'Units','normalized',...
 'Position',[0.35 0.4 0.3 0.1],...
 'string','AMPLIFICATOARE',...
 'Callback','close;AO_inversor(R1,R2,VAL,Val,A,N,F,semnal)');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.35 0.2 0.3 0.1],...
 'backgroundcolor','#F0F0F0',...
 'FontSize',12,...
 'String','Melinte Cosmin'); 
